### ISSUE TITLE
Support protobuf v4

### ISSUE THREAD

**Issue by pdgendt** [fischor/protogen-python#13]
The latest version of `protobuf` is `4.25.1`:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
protogen 0.3.0 requires protobuf<4.0.0,>=3.20.3, but you have protobuf 4.25.1 which is incompatible.
```

**Comment by fischor** [comment]
There was a PR that loosened that requirement the 0.3.0 value has in place: https://github.com/fischor/protogen-python/pull/10

It is now
https://github.com/fischor/protogen-python/blob/5bb14dc549415f0f46e4ccb88815925668c6d2ff/pyproject.toml#L21C16-L21C22

I just made a new release v0.3.1 that includes these changes. If you update to v0.3.1 it should work

**Comment by pdgendt** [comment]
Great, thanks! Would it be possible to bump the pip package too?

**Comment by pdgendt** [comment]
Thanks for updating the version!

Small remark, the first example on the project's README doesn't work with the latest version :)
