### ISSUE TITLE
Implement relative type resolution

### ISSUE THREAD

**Issue by fischor** [fischor/protogen-python#2]
Implement relative type resolution (with C++ scoping rules) for cases where a `type_name` might not start with a `"."`.

https://github.com/fischor/protogen-python/blob/389395928c06679f09e2c50c3342862cc861cd3b/protogen/__init__.py#L187-L208

That mechanism should also be made available to the user of protogen. It can be useful for cases where types are referenced in annotations, e.g. `google.longrunning.operation_info` or similar.

**Comment by CyberInvestigator** [comment]
facing the  same issue - any updates on this ?

**Comment by fischor** [comment]
@CyberInvestigator  Which issue are you facing? Is the exception in Line 195 thrown for you? If so, can you provide an example setup (proto files, folder structure and `protoc` call) with that this exception occurs?

**Comment by fischor** [comment]
This features was added with 4e754dda462afd57abb16851a6cd032ac5d33233
