### ISSUE TITLE
Document how to handle extensions

### ISSUE THREAD

**Issue by fischor** [fischor/protogen-python#3]
You need to import their descriptors (generated with the official Proto plugin) that register the extensions.
Then they are automatically available in the e.g. `MessageOptions` fields.

**Comment by Fraser-Isbester** [comment]
Hey! Great lib, can you elaborate on this? Happy to help with implementation.

**Comment by fischor** [comment]
There is nothing to implement, its just needs to be documented better since its not super intuitive. I can try to add documentation for this over the weekend.

But in the meantime here is the quick guide:

Define the extension, e.g.:

```proto
// this file is named operations.proto

extend google.protobuf.MethodOptions {
  trainai.longrunning.OperationInfo operation_info = 1049;
}

message OperationInfo {
    string response_type = 1;
    string metadata_type = 2;
}
```

You need to run the official Python compiler over the file/package that contains the extension first before using it. This will generate for the above example a `operations_pb2.py` file. For the extension it contains the following:

```python
# operation_pb2.py

OPERATION_INFO_FIELD_NUMBER = 1049
operation_info = _descriptor.FieldDescriptor(
  name='operation_info', full_name='trainai.longrunning.operation_info', index=0,
  number=1049, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
```

Now you can start using that extension is your plugin. You need to import the Python module that defines the extension. This will register the extension in the type/extension registry (of the offical `protobuf ` lib). This should happen before the request from `protoc` is read (place it somewhere in the beginning of your plugin to be on the safe side).

```python
import trainai.longrunning.operations_pb2

# Somewhere after run your plugin
protogen.Options(...).run(_generate)
```

Now you can use the extension values. In the example I have choosen its a message option that would be used like that in proto:

```proto
 rpc CreateFolder(CreateFolderRequest) returns (trainai.longrunning.Operation) {
        option (google.api.http) = {
            post: "/v1/folders",
            body: "folder"
        };
        option (trainai.longrunning.operation_info) = { // <-- here
            response_type: "Folder"
            metadata_type: "CreateFolderMetadata"
        };
  }
```

and can be parsed in your plugin. I often define helper method for this. Here is an excerpt from a plugin I have written:

```python
from dataclasses import dataclass
from typing import Optional
import protogen

import trainai.longrunning.operations_pb2

@dataclass
class OperationInfo():
    response_type: protogen.Message
    metadata_type: protogen.Message

def operation_info(gen: protogen.Plugin,
                   method: protogen.Method) -> Optional[OperationInfo]:
    pb = None
    for fd, msg_or_none in method.proto.options.ListFields(): # <-- The extension values can be found inside here
        if fd.number == trainai.longrunning.operations_pb2.OPERATION_INFO_FIELD_NUMBER:
            pb = msg_or_none
            break
    if pb is None:
       #  extension has not been set on that method
        return None 
    # ...
    # pb is at t a protobuf Message. In my example the extensions message type in OperationInfo.
    # You can its fields. In my example this would be pb.response_type and pb.metadata_type
    # ...
    return OperationInfo(response_type, metadata_type)
```

Let me know if that helps or what is missing for you. As said, if I find time over the weekend I will add more extensive documentation and maybe provide an example.

**Comment by Fraser-Isbester** [comment]
Hey @fischor,
Awesome, yeah this worked like a charm. Thank you!

**Comment by fischor** [comment]
See #14
